version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${DBADMIN_MAIL}
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8080:80"
        depends_on:
            - postgres

volumes:
    postgres_data:
